[package]
name = "micro_kernel_syscall_api"
version = "0.1.0"
edition = "2021"
authors = ["Youjie Zheng <zyj578335934@gmail.com>"]
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html


[features]
default = ["microkernel"]

# monolithic = []
microkernel = []


[dependencies]
cfg-if = "1.0"
axlog = { git = "https://github.com/Starry-OS/axlog.git" }
axruntime = { git = "https://github.com/Starry-OS/axruntime.git" }
axhal = { git = "https://github.com/Starry-OS/axhal.git" }
axtask = { git = "https://github.com/Starry-OS/axtask.git" }
axconfig = { git = "https://github.com/Starry-OS/axconfig.git" }

lazy_init = { git = "https://github.com/Starry-OS/lazy_init.git" }
spinlock = { git = "https://github.com/Starry-OS/spinlock.git" }
axerrno = { git = "https://github.com/Starry-OS/axerrno.git" }
numeric-enum-macro = { git = "https://github.com/mexus/numeric-enum-macro" }
bitflags = "2.0"
rand = { version = "0.8.5", default-features = false, features = ["small_rng"] }
num_enum = { version = "0.5.11", default-features = false }